spring.application.name=urlshortnerproject
spring.datasource.url=jdbc:mysql://localhost:3306/urlshortenerdb
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=174e69faba9efc5c4a8af8b55839f9821fe3e5d8847ffaaae2dddc2e12de2336
jwt.expiration=172800000

logging.level.org.springframework.security=DEBUG
logging.level.org.url.shortener=DEBUG
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework=DEBUG
#logging.level.org.springframework.web.servlet=TRACE